
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ArmConverter/ArmConverter.csproj
    - name: Build
      run: dotnet build ArmConverter/ArmConverter.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ArmConverter/ArmConverter.csproj --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish ArmConverter/ArmConverter.csproj
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ArmConverter.Net
        path: /home/runner/work/ArmConverter.Net/ArmConverter.Net/ArmConverter/bin/Debug/net5.0/publish/ArmConverter.dll
