name: .NET

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore Dependencies
      run: dotnet restore ArmConverter/ArmConverter.csproj
    
    - name: Build
      run: dotnet build ArmConverter/ArmConverter.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ArmConverter/ArmConverter.csproj --no-restore --verbosity normal
    
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: ArmConverter.dll
        path: /home/runner/work/ArmConverter.Net/ArmConverter.Net/ArmConverter/bin/Debug/net5.0/ArmConverter.dll

    - name: Upload Documentation File
      uses: actions/upload-artifact@v2
      with:
        name: ArmConverter.xml
        path: /home/runner/work/ArmConverter.Net/ArmConverter.Net/ArmConverter/bin/Release/net5.0/ArmConverter.xml
